import { DEFAULT_LOCALE, loadPreferredLocale, type SupportedLocale } from '@/lib/locale';

export type ProfessionalFinancialCopy = {
  paymentEyebrow: string; paymentTitle: string; paymentDescription: string; addDestination: string; loadingDestinations: string; updatingDestination: string; defaultLabel: string; providerPending: string; edit: string; disable: string; noDestination: string; editDestination: string; type: string; label: string; bankTransfer: string; bankName: string; accountDisplay: string; ifsc: string; defaultActive: string; saving: string; saveDestination: string; closeEditor: string; disableConfirm: (label: string) => string;
  reimbursementEyebrow: string; reimbursementTitle: string; reimbursementDescription: string; issuing: string; issueRecord: string; issuingStatus: string; copiedStatus: string; verifiedCredentialsRequired: string; issueFailed: string; copyFailed: string; issuedTitle: string; issuedDetail: (invoice: string) => string; openVerification: string; copied: string; copyLink: string; printPdf: string; recordTitle: string; invoicePrefix: string; recordDescription: string; documentId: string; issued: string; qrLabel: string; verificationUrl: string; disclaimer: string;
};

const copies: Record<SupportedLocale, ProfessionalFinancialCopy> = {
  'en-IN': {
    paymentEyebrow:'Payment destinations', paymentTitle:'Where patients can pay you', paymentDescription:'These destinations belong to your physiotherapist account. Provider-managed settlement remains externally activated and cannot be configured here.', addDestination:'Add destination', loadingDestinations:'Loading payment destinations…', updatingDestination:'Updating payment destination.', defaultLabel:'Default', providerPending:'Provider activation pending', edit:'Edit', disable:'Disable', noDestination:'No payment destination configured yet.', editDestination:'Edit destination', type:'Type', label:'Label', bankTransfer:'Bank transfer', bankName:'Bank name', accountDisplay:'Account display', ifsc:'IFSC', defaultActive:'Use as default active destination', saving:'Saving…', saveDestination:'Save destination', closeEditor:'Close payment destination editor', disableConfirm:(label)=>`Disable ${label}?`,
    reimbursementEyebrow:'Professional reimbursement document', reimbursementTitle:'Create an insurer-ready verification record', reimbursementDescription:'Issuance is created from this immutable finalized-invoice snapshot. Patient and clinical details are never exposed by the public verification page.', issuing:'Issuing…', issueRecord:'Issue verification record', issuingStatus:'Issuing reimbursement verification record.', copiedStatus:'Verification link copied.', verifiedCredentialsRequired:'Verified professional credentials are required before a reimbursement document can be issued.', issueFailed:'Reimbursement document issuance failed. Confirm this is your finalized invoice and try again.', copyFailed:'Could not copy the verification link on this device.', issuedTitle:'Verification record issued', issuedDetail:(invoice)=>`Invoice ${invoice} now has an immutable public verification token. Issuing again returns the same record rather than creating a second document.`, openVerification:'Open verification page', copied:'Copied', copyLink:'Copy verification link', printPdf:'Print / save PDF', recordTitle:'PhysioBill reimbursement verification record', invoicePrefix:'Invoice', recordDescription:'This record binds the finalized invoice to an immutable PhysioBill verification token. Scan the code or open the verification URL to confirm document provenance and the verified professional credentials captured at issuance.', documentId:'Document ID', issued:'Issued', qrLabel:'Reimbursement verification QR code', verificationUrl:'Verification URL', disclaimer:'Verification confirms PhysioBill document provenance and captured professional credentials only. It does not prove insurer approval, reimbursement eligibility, payment settlement, or legal acceptance. Patient and clinical details are not disclosed by the public verification endpoint.'
  },
  'hi-IN': {
    paymentEyebrow:'भुगतान गंतव्य', paymentTitle:'मरीज़ आपको कहाँ भुगतान कर सकते हैं', paymentDescription:'ये भुगतान गंतव्य आपके फिजियोथेरेपिस्ट खाते से जुड़े हैं। प्रदाता-प्रबंधित सेटलमेंट बाहरी सक्रियण के अधीन है और यहाँ कॉन्फ़िगर नहीं किया जा सकता।', addDestination:'गंतव्य जोड़ें', loadingDestinations:'भुगतान गंतव्य लोड हो रहे हैं…', updatingDestination:'भुगतान गंतव्य अपडेट हो रहा है।', defaultLabel:'डिफ़ॉल्ट', providerPending:'प्रदाता सक्रियण लंबित', edit:'संपादित करें', disable:'अक्षम करें', noDestination:'अभी कोई भुगतान गंतव्य कॉन्फ़िगर नहीं है।', editDestination:'गंतव्य संपादित करें', type:'प्रकार', label:'लेबल', bankTransfer:'बैंक ट्रांसफ़र', bankName:'बैंक का नाम', accountDisplay:'खाता प्रदर्शन', ifsc:'IFSC', defaultActive:'डिफ़ॉल्ट सक्रिय गंतव्य के रूप में उपयोग करें', saving:'सहेजा जा रहा है…', saveDestination:'गंतव्य सहेजें', closeEditor:'भुगतान गंतव्य संपादक बंद करें', disableConfirm:(label)=>`${label} को अक्षम करें?`,
    reimbursementEyebrow:'पेशेवर प्रतिपूर्ति दस्तावेज़', reimbursementTitle:'बीमाकर्ता-तैयार सत्यापन रिकॉर्ड बनाएँ', reimbursementDescription:'यह रिकॉर्ड अंतिम चालान के अपरिवर्तनीय स्नैपशॉट से बनाया जाता है। सार्वजनिक सत्यापन पृष्ठ पर मरीज या क्लिनिकल विवरण प्रदर्शित नहीं होते।', issuing:'जारी किया जा रहा है…', issueRecord:'सत्यापन रिकॉर्ड जारी करें', issuingStatus:'प्रतिपूर्ति सत्यापन रिकॉर्ड जारी किया जा रहा है।', copiedStatus:'सत्यापन लिंक कॉपी किया गया।', verifiedCredentialsRequired:'प्रतिपूर्ति दस्तावेज़ जारी करने से पहले सत्यापित पेशेवर प्रमाण-पत्र आवश्यक हैं।', issueFailed:'प्रतिपूर्ति दस्तावेज़ जारी नहीं हो सका। पुष्टि करें कि यह आपका अंतिम चालान है और पुनः प्रयास करें।', copyFailed:'इस डिवाइस पर सत्यापन लिंक कॉपी नहीं हो सका।', issuedTitle:'सत्यापन रिकॉर्ड जारी हुआ', issuedDetail:(invoice)=>`चालान ${invoice} के लिए अपरिवर्तनीय सार्वजनिक सत्यापन टोकन जारी हो गया है। दोबारा जारी करने पर नया दस्तावेज़ नहीं बनेगा।`, openVerification:'सत्यापन पृष्ठ खोलें', copied:'कॉपी हुआ', copyLink:'सत्यापन लिंक कॉपी करें', printPdf:'प्रिंट / PDF सहेजें', recordTitle:'PhysioBill प्रतिपूर्ति सत्यापन रिकॉर्ड', invoicePrefix:'चालान', recordDescription:'यह रिकॉर्ड अंतिम चालान को अपरिवर्तनीय PhysioBill सत्यापन टोकन से जोड़ता है। कोड स्कैन करें या सत्यापन URL खोलकर दस्तावेज़ स्रोत और जारी करते समय कैप्चर किए गए सत्यापित पेशेवर प्रमाण-पत्र की पुष्टि करें।', documentId:'दस्तावेज़ ID', issued:'जारी किया गया', qrLabel:'प्रतिपूर्ति सत्यापन QR कोड', verificationUrl:'सत्यापन URL', disclaimer:'सत्यापन केवल PhysioBill दस्तावेज़ स्रोत और कैप्चर किए गए पेशेवर प्रमाण-पत्र की पुष्टि करता है। यह बीमाकर्ता स्वीकृति, प्रतिपूर्ति पात्रता, भुगतान सेटलमेंट या कानूनी स्वीकृति का प्रमाण नहीं है। सार्वजनिक सत्यापन में मरीज और क्लिनिकल विवरण उजागर नहीं होते।'
  },
  'gu-IN': {
    paymentEyebrow:'ચુકવણી ગંતવ્ય', paymentTitle:'દર્દીઓ તમને ક્યાં ચૂકવણી કરી શકે', paymentDescription:'આ ચુકવણી ગંતવ્ય તમારા ફિઝિયોથેરાપિસ્ટ ખાતા સાથે જોડાયેલા છે. પ્રદાતા સંચાલિત સેટલમેન્ટ બાહ્ય સક્રિયકરણ હેઠળ છે અને અહીં ગોઠવી શકાતું નથી.', addDestination:'ગંતવ્ય ઉમેરો', loadingDestinations:'ચુકવણી ગંતવ્ય લોડ થઈ રહ્યા છે…', updatingDestination:'ચુકવણી ગંતવ્ય અપડેટ થઈ રહ્યું છે.', defaultLabel:'ડિફૉલ્ટ', providerPending:'પ્રદાતા સક્રિયકરણ બાકી', edit:'સંપાદિત કરો', disable:'નિષ્ક્રિય કરો', noDestination:'હજુ કોઈ ચુકવણી ગંતવ્ય ગોઠવાયેલું નથી.', editDestination:'ગંતવ્ય સંપાદિત કરો', type:'પ્રકાર', label:'લેબલ', bankTransfer:'બેંક ટ્રાન્સફર', bankName:'બેંકનું નામ', accountDisplay:'ખાતા પ્રદર્શન', ifsc:'IFSC', defaultActive:'ડિફૉલ્ટ સક્રિય ગંતવ્ય તરીકે ઉપયોગ કરો', saving:'સાચવી રહ્યું છે…', saveDestination:'ગંતવ્ય સાચવો', closeEditor:'ચુકવણી ગંતવ્ય સંપાદક બંધ કરો', disableConfirm:(label)=>`${label} નિષ્ક્રિય કરવું?`,
    reimbursementEyebrow:'વ્યાવસાયિક વળતર દસ્તાવેજ', reimbursementTitle:'વીમાકર્તા માટે તૈયાર ચકાસણી રેકોર્ડ બનાવો', reimbursementDescription:'આ રેકોર્ડ અંતિમ ઇન્વૉઇસના અપરિવર્તનીય સ્નૅપશૉટ પરથી બને છે. જાહેર ચકાસણી પૃષ્ઠ દર્દી અથવા ક્લિનિકલ વિગતો જાહેર કરતું નથી.', issuing:'જારી થઈ રહ્યું છે…', issueRecord:'ચકાસણી રેકોર્ડ જારી કરો', issuingStatus:'વળતર ચકાસણી રેકોર્ડ જારી થઈ રહ્યો છે.', copiedStatus:'ચકાસણી લિંક કૉપી થઈ.', verifiedCredentialsRequired:'વળતર દસ્તાવેજ જારી કરતા પહેલા ચકાસાયેલ વ્યાવસાયિક પ્રમાણપત્રો જરૂરી છે.', issueFailed:'વળતર દસ્તાવેજ જારી થઈ શક્યો નથી. ખાતરી કરો કે આ તમારું અંતિમ ઇન્વૉઇસ છે અને ફરી પ્રયાસ કરો.', copyFailed:'આ ઉપકરણ પર ચકાસણી લિંક કૉપી થઈ શકી નથી.', issuedTitle:'ચકાસણી રેકોર્ડ જારી થયો', issuedDetail:(invoice)=>`ઇન્વૉઇસ ${invoice} માટે અપરિવર્તનીય જાહેર ચકાસણી ટોકન જારી થયું છે. ફરી જારી કરવાથી નવો દસ્તાવેજ બનશે નહીં.`, openVerification:'ચકાસણી પૃષ્ઠ ખોલો', copied:'કૉપી થયું', copyLink:'ચકાસણી લિંક કૉપી કરો', printPdf:'પ્રિન્ટ / PDF સાચવો', recordTitle:'PhysioBill વળતર ચકાસણી રેકોર્ડ', invoicePrefix:'ઇન્વૉઇસ', recordDescription:'આ રેકોર્ડ અંતિમ ઇન્વૉઇસને અપરિવર્તનીય PhysioBill ચકાસણી ટોકન સાથે જોડે છે. કોડ સ્કૅન કરો અથવા ચકાસણી URL ખોલીને દસ્તાવેજનું સ્ત્રોત અને જારી કરતી વખતે કૅપ્ચર થયેલા ચકાસાયેલ વ્યાવસાયિક પ્રમાણપત્રોની ખાતરી કરો.', documentId:'દસ્તાવેજ ID', issued:'જારી થયું', qrLabel:'વળતર ચકાસણી QR કોડ', verificationUrl:'ચકાસણી URL', disclaimer:'ચકાસણી માત્ર PhysioBill દસ્તાવેજનું સ્ત્રોત અને કૅપ્ચર થયેલા વ્યાવસાયિક પ્રમાણપત્રોની પુષ્ટિ કરે છે. તે વીમાકર્તા મંજૂરી, વળતર પાત્રતા, ચુકવણી સેટલમેન્ટ અથવા કાનૂની સ્વીકૃતિનો પુરાવો નથી. જાહેર ચકાસણી દર્દી અને ક્લિનિકલ વિગતો જાહેર કરતી નથી.'
  }
};

export function professionalFinancialCopy(locale: SupportedLocale) { return copies[locale] ?? copies[DEFAULT_LOCALE]; }
export async function loadProfessionalFinancialLocale() { try { return await loadPreferredLocale(); } catch { return DEFAULT_LOCALE; } }
