import { useEffect, useState } from 'react';
import { Copy, ExternalLink, FileCheck2, Printer, ShieldCheck } from 'lucide-react';
import { VerificationQr } from '@/Components/VerificationQr';
import { issueReimbursementDocument, reimbursementVerificationPath, reimbursementVerificationUrl, type IssuedReimbursementDocument } from '@/lib/reimbursement-documents';
import { DEFAULT_LOCALE, type SupportedLocale } from '@/lib/locale';
import { loadProfessionalFinancialLocale, professionalFinancialCopy } from '@/lib/professional-financial-locale';

const actionFocus='focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2';

export function ReimbursementDocumentPanel({invoiceId}:{invoiceId:string}){
 const[document,setDocument]=useState<IssuedReimbursementDocument|null>(null); const[busy,setBusy]=useState(false); const[error,setError]=useState<string|null>(null); const[copied,setCopied]=useState(false); const[locale,setLocale]=useState<SupportedLocale>(DEFAULT_LOCALE); const copy=professionalFinancialCopy(locale);
 useEffect(()=>{let active=true;void(async()=>{const next=await loadProfessionalFinancialLocale();if(active)setLocale(next)})();return()=>{active=false}},[]);
 const issueDocument=async()=>{setBusy(true);setError(null);try{setDocument(await issueReimbursementDocument(invoiceId))}catch(caught){const message=caught instanceof Error?caught.message:'';setError(message.includes('Verified professional credentials')?copy.verifiedCredentialsRequired:copy.issueFailed)}finally{setBusy(false)}};
 const copyVerificationLink=async()=>{if(!document)return;try{await navigator.clipboard.writeText(reimbursementVerificationUrl(document.verificationToken));setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{setError(copy.copyFailed)}};
 const verificationUrl=document?reimbursementVerificationUrl(document.verificationToken):null;
 return <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6" aria-busy={busy}>
  <div className="no-print flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="flex items-center gap-2 text-primary"><FileCheck2 size={18} aria-hidden="true"/><p className="text-xs font-extrabold uppercase tracking-[.14em]">{copy.reimbursementEyebrow}</p></div><h2 className="mt-2 text-lg font-extrabold">{copy.reimbursementTitle}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy.reimbursementDescription}</p></div>{!document&&<button type="button" disabled={busy} onClick={()=>void issueDocument()} className={`min-h-11 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50 ${actionFocus}`}>{busy?copy.issuing:copy.issueRecord}</button>}</div>
  <div className="sr-only" role="status" aria-live="polite">{busy?copy.issuingStatus:copied?copy.copiedStatus:''}</div>{error&&<div role="alert" className="no-print mt-4 rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
  {document&&verificationUrl&&<><div className="no-print mt-5 rounded-2xl border border-emerald-200 bg-emerald-50/70 p-4 text-emerald-950" role="status"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0" aria-hidden="true"/><div className="min-w-0 flex-1"><p className="font-bold">{copy.issuedTitle}</p><p className="mt-1 break-words text-sm leading-6">{copy.issuedDetail(document.invoiceNumber)}</p><div className="mt-3 flex flex-wrap gap-2"><a href={reimbursementVerificationPath(document.verificationToken)} target="_blank" rel="noreferrer" className={`inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-300 bg-white px-3 py-2 text-xs font-semibold ${actionFocus}`}><ExternalLink size={14} aria-hidden="true"/>{copy.openVerification}</a><button type="button" onClick={()=>void copyVerificationLink()} className={`inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-300 bg-white px-3 py-2 text-xs font-semibold ${actionFocus}`}><Copy size={14} aria-hidden="true"/>{copied?copy.copied:copy.copyLink}</button><button type="button" onClick={()=>window.print()} className={`inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-300 bg-white px-3 py-2 text-xs font-semibold ${actionFocus}`}><Printer size={14} aria-hidden="true"/>{copy.printPdf}</button></div></div></div></div>
   <article className="mt-6 rounded-2xl border bg-white p-6 text-slate-950 print:mt-0 print:rounded-none print:border-0 print:p-0" style={{breakBefore:'page'}}><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 max-w-xl"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-slate-500">{copy.recordTitle}</p><h3 className="mt-2 break-words text-2xl font-extrabold">{copy.invoicePrefix} {document.invoiceNumber}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy.recordDescription}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div className="min-w-0"><dt className="font-semibold text-slate-500">{copy.documentId}</dt><dd className="mt-1 break-all font-mono text-xs">{document.documentId}</dd></div><div><dt className="font-semibold text-slate-500">{copy.issued}</dt><dd className="mt-1">{new Date(document.issuedAt).toLocaleString(locale)}</dd></div></dl></div><div className="shrink-0 self-start rounded-2xl border bg-white p-3"><VerificationQr value={verificationUrl} label={copy.qrLabel}/></div></div><div className="mt-6 rounded-xl border bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{copy.verificationUrl}</p><p className="mt-2 break-all font-mono text-xs leading-5">{verificationUrl}</p></div><p className="mt-5 text-xs leading-5 text-slate-500">{copy.disclaimer}</p></article></>}
  <p className="no-print mt-4 text-xs leading-5 text-muted-foreground">{copy.disclaimer}</p>
 </section>;
}
